class accounts {
  Map<String, String> acct = {
    'Purchase Local 12 %': 'Purchase Accounts',
    'Purchase Interstate 12%': 'Purchase Accounts',
    'Purchase Local 0%': 'Purchase Accounts',
    'Purchase Interstate 0%': 'Purchase Accounts',
    'Purchase (Composition)': 'Purchase Accounts',
    'Purchase Exempt (Unregistered Dealer)': 'Purchase Accounts',
    'Purchase Local (Exempt Registered)': 'Purchase Accounts',
    'Purchase Taxable (Unregistered Dealer)': 'Purchase Accounts',
    'Purchase Nil Rated (Unregistered Dealer)': 'Purchase Accounts',
    'Purchase Reverse Charge': 'Purchase Accounts',
    'Purchase Import Taxable 12%': 'Purchase Accounts',
    'Purchase Import Exempt': 'Purchase Accounts',
    'Purchase Import Nil Rated': 'Purchase Accounts',
    'Purchase (Own Branch)': 'Purchase Accounts',
    'Purchase Return': 'Purchase Accounts',
    'Sales Local 12 % (Registered)': 'Sales Account',
    'Sales Interstate 12%': 'Sales Account',
    'Sales Local Nil Rated': 'Sales Account',
    'Sales Interstate Nil Rated': 'Sales Account',
    'Salers Export With Bond': 'Sales Account',
    'Salers Export Taxable': 'Sales Account',
    'Export (0%)': 'Sales Account',
    'Sales Local (Exempt Registered)': 'Sales Account',
    'Sale To Consumer (Taxable 12%)': 'Sales Account',
    'Sale To Consumer (0%)': 'Sales Account',
    'Sale To Consumer (Exempt)': 'Sales Account',
    'Sales (Own Branch)': 'Sales Account',
    'Sale Return': 'Sales Account',
    'INPUT CGST SGST IGST CESS': 'Duties and Taxes',
    'OUTPUT GST SGST IGST CESS': 'Duties and Taxes',
    'Excise Duty Payable etc': 'Duties and Taxes',
    'Service Tax Payable ': 'Duties and Taxes',
    'TDS Payables ': 'Duties and Taxes',
    'Input Vat Accounts ': 'Duties and Taxes',
    'Output Vat Accounts ': 'Duties and Taxes',
    'Cenvat Accounts': 'Duties and Taxes',
    'Sale tax': 'Duties and Taxes',
    'Income Tax': 'Duties and Taxes',
    'VAT Payable': 'Duties and Taxes',
    'Labor': 'Direct Expenses OR Expenses(Direct)',
    'Power': 'Direct Expenses OR Expenses(Direct)',
    'Electricity Expense (Factory)': 'Direct Expenses OR Expenses(Direct)',
    'Loading Unloading Expense': 'Direct Expenses OR Expenses(Direct)',
    'Warehousing Expenses': 'Direct Expenses OR Expenses(Direct)',
    'Custom Clearing Charges': 'Direct Expenses OR Expenses(Direct)',
    'Carriage': 'Direct Expenses OR Expenses(Direct)',
    'Freight & Cartage': 'Direct Expenses OR Expenses(Direct)',
    'Import duty': 'Direct Expenses OR Expenses(Direct)',
    'Wages': 'Direct Expenses OR Expenses(Direct)',
    'Coal & Fuel': 'Direct Expenses OR Expenses(Direct)',
    'Coal, Gas & Water of Factory': 'Direct Expenses OR Expenses(Direct)',
    'Consumed Material': 'Direct Expenses OR Expenses(Direct)',
    'Export Duty': 'Direct Expenses OR Expenses(Direct)',
    'Wages on Production': 'Direct Expenses OR Expenses(Direct)',
    'Delivery Charges(In Purchase Bill': 'Direct Expenses OR Expenses(Direct)',
    'Rounded Off': 'Indirect Expenses OR Expense(Indirect)',
    'Salary': 'Indirect Expenses OR Expense(Indirect)',
    'Advertisement Expense': 'Indirect Expenses OR Expense(Indirect)',
    'Maintenance Expense': 'Indirect Expenses OR Expense(Indirect)',
    'Rent Expense': 'Indirect Expenses OR Expense(Indirect)',
    'Director Remuneration Expense': 'Indirect Expenses OR Expense(Indirect)',
    'Bad Debts': 'Indirect Expenses OR Expense(Indirect)',
    'Printing Expense': 'Indirect Expenses OR Expense(Indirect)',
    'Stationary Expense': 'Indirect Expenses OR Expense(Indirect)',
    'Foreign Exchange fluctuation': 'Indirect Expenses OR Expense(Indirect)',
    'Audit Fees': 'Indirect Expenses OR Expense(Indirect)',
    'Professional Charges': 'Indirect Expenses OR Expense(Indirect)',
    'Legal Expenses/Charges': 'Indirect Expenses OR Expense(Indirect)',
    'Depreciation Expenses': 'Indirect Expenses OR Expense(Indirect)',
    'Interest Expense': 'Indirect Expenses OR Expense(Indirect)',
    'Penalty': 'Indirect Expenses OR Expense(Indirect)',
    'Royalty': 'Indirect Expenses OR Expense(Indirect)',
    'Bank charges': 'Indirect Expenses OR Expense(Indirect)',
    'Commission allowed': 'Indirect Expenses OR Expense(Indirect)',
    'Discount allowed': 'Indirect Expenses OR Expense(Indirect)',
    'Donation & charity': 'Indirect Expenses OR Expense(Indirect)',
    'Free sample': 'Indirect Expenses OR Expense(Indirect)',
    'Insurance premium': 'Indirect Expenses OR Expense(Indirect)',
    'Interest on loan': 'Indirect Expenses OR Expense(Indirect)',
    'Legal charge': 'Indirect Expenses OR Expense(Indirect)',
    'Loss by fire': 'Indirect Expenses OR Expense(Indirect)',
    'Postage & courier': 'Indirect Expenses OR Expense(Indirect)',
    'Repair charge': 'Indirect Expenses OR Expense(Indirect)',
    'Taxi fare': 'Indirect Expenses OR Expense(Indirect)',
    'Telephone charge': 'Indirect Expenses OR Expense(Indirect)',
    'Travelling expenses': 'Indirect Expenses OR Expense(Indirect)',
    'Outstanding expenses': 'Indirect Expenses OR Expense(Indirect)',
    'Accrued expenses': 'Indirect Expenses OR Expense(Indirect)',
    'Bad debt': 'Indirect Expenses OR Expense(Indirect)',
    'Loss on theft': 'Indirect Expenses OR Expense(Indirect)',
    'depriciation': 'Indirect Expenses OR Expense(Indirect)',
    'Coffee Expenses': 'Indirect Expenses OR Expense(Indirect)',
    'Coke Expenses': 'Indirect Expenses OR Expense(Indirect)',
    'Manager’s Commission': 'Indirect Expenses OR Expense(Indirect)',
    'UPTT': 'Indirect Expenses OR Expense(Indirect)',
    'Fuel Expenses A/c': 'Indirect Expenses OR Expense(Indirect)',
    'Liabilty of Expenses': 'Indirect Expenses OR Expense(Indirect)',
    'Preliminary Expenses A/c': 'Indirect Expenses OR Expense(Indirect)',
    'Professional Fees': 'Indirect Expenses OR Expense(Indirect)',
    'Discount Received': 'Indirect Income OR Income(Indirect)',
    'Interest on Investment': 'Indirect Income OR Income(Indirect)',
    'Cash': 'Already Created in Tally',
    'Profit and Loss Account': 'Already Created in Tally',
    'Canara Bank': 'Bank Account',
    'Axis Bank': 'Bank Account',
    'Security Deposit': 'Deposit Account',
    'Electricity Deposit': 'Deposit Account',
    'Rent Deposit': 'Deposit Account',
    'Share Capital': 'Capital A/c',
    'Partner Capital Account': 'Capital A/c',
    'Partner Current Account': 'Capital A/c',
    'Proprietor Account': 'Capital A/c',
    'Drawings ': 'Capital A/c',
    'Life insurance': 'Capital A/c',
    'Equity Capital A/c': 'Capital A/c',
    'Partners Capital A/c': 'Capital A/c',
    'Prepaid Maintenance Expense': 'Current Assets',
    'Prepaid Expense': 'Current Assets',
    'Prepaid Rent': 'Current Assets',
    'Prepaid Insurance Charges': 'Current Assets',
    'Interest Receivables': 'Current Assets',
    'Bill receivable': 'Current Assets',
    'Accrued income': 'Current Assets',
    'Mutual Fund': 'Current Assets',
    'CGST SGST IGST Credit': '',
    'Bill drawn': 'Current Liabilities',
    'Bill Payable': 'Current Liabilities',
    'CGST SGST IGST  Payable': 'Current Liabilities',
    'Debenture A/c': 'Loans Liabilities',
    'Loans From Bank': 'Loans Liabilities',
    'Loans From Outside Party': 'Loans Liabilities',
    'Loans From Aravind(Friend)': 'Loans Liabilities',
    'Furniture': 'Fixed Assets',
    'Machine': 'Fixed Assets',
    'Plant and Machinery': 'Fixed Assets',
    'Mobile': 'Fixed Assets',
    'Computers': 'Fixed Assets',
    'Furniture and Fittings': 'Fixed Assets',
    'Car': 'Fixed Assets',
    'Scooter': 'Fixed Assets',
    'Laptops': 'Fixed Assets',
    'Office lighting': 'Fixed Assets',
    'Land & Building': 'Fixed Assets',
    'Good will': 'Fixed Assets',
    'Factory lighting': 'Fixed Assets',
    'Air Conditioner': 'Fixed Assets',
    'Accumulated depriciation': 'Fixed Assets',
    'Petty Cash': 'Cash in Hand ',
    'Investment in Shares': 'Investments',
    'Investment in Bonds': 'Investments',
    'Investment in Property/Plot etc.': 'Investments',
    'Long term investment': 'Investments',
    'Short Term Investment': 'Investments',
    'Stock': 'Stock-in-hand',
    'Closing Stock': 'Stock-in-hand',
    'Consignment Stock': 'Stock-in-hand',
    'Opening Stock': 'Stock-in-hand',
    'Preliminary Expenses': 'Misc. Expense (ASSET)',
    'Suspense': 'Suspense A/c',
    'General Reserve': 'Reserve & Surplus',
    'Capital Reserve ': 'Reserve & Surplus',
    'Capital Reserve A/c': 'Reserve & Surplus',
    'Investment Allowance Reserve A/c': 'Reserve & Surplus',
    'Share Premium A/c': 'Reserve & Surplus',
    'Reverse and Surplus': 'Reserve & Surplus',
    'Provision for Tax': 'Provisions',
    'Provision for Expense': 'Provisions',
    'Provision for Sinking Fund': 'Provisions',
    'Provision for Bad Debts': 'Sundry Debtors',
    'General Reserve': 'Retained Earring',
    'Share Premium': 'Retained Earring',
    'Freight Charges Income': 'Direct Incomes OR Income(Direct)',
    'Delivery Charges Income': 'Direct Incomes OR Income(Direct)',
    'Transporation Charges Income': 'Direct Incomes OR Income(Direct)',
    'Professional Charges Income': 'Direct Incomes OR Income(Direct)',
    'Consultancy Charges Income': 'Direct Incomes OR Income(Direct)',
    'Maintainance Service Income': 'Direct Incomes OR Income(Direct)'
  };
  List<String>? groups = [
    'Purchase Accounts',
    'Sales Account',
    'Duties and Taxes',
    'Direct Expenses OR Expenses(Direct)',
    'Indirect Expenses OR Expense(Indirect)',
    'Indirect Income OR Income(Indirect)',
    'Already Created in Tally',
    'Bank Account',
    'Deposit Account',
    'Capital A/c',
    'Current Assets',
    'Current Liabilities',
    'Loans Liabilities',
    'Fixed Assets',
    'Cash in Hand ',
    'Investments',
    'Stock-in-hand',
    'Misc. Expense (ASSET)',
    'Suspense A/c',
    'Reserve & Surplus',
    'Provisions',
    'Sundry Debtors',
    'Retained Earring',
    'Direct Incomes OR Income(Direct)'
  ];
}
